// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEh-220a5ZOd8NLE-e_tJVuv00lXqfS44',
    appId: '1:101486068607:web:4e04a3e35ee8bd492b104a',
    messagingSenderId: '101486068607',
    projectId: 'dokumandenemesi',
    authDomain: 'dokumandenemesi.firebaseapp.com',
    storageBucket: 'dokumandenemesi.appspot.com',
    measurementId: 'G-YGLR38QG93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCI1oh2kJGpRu7hesbPLZQo7kSZPMne2I',
    appId: '1:101486068607:android:d634886d3145ba4a2b104a',
    messagingSenderId: '101486068607',
    projectId: 'dokumandenemesi',
    storageBucket: 'dokumandenemesi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhNxT7CTwQuXqyEIUCmap2hzoMTA_hE9U',
    appId: '1:101486068607:ios:6bf8750aa0a604732b104a',
    messagingSenderId: '101486068607',
    projectId: 'dokumandenemesi',
    storageBucket: 'dokumandenemesi.appspot.com',
    iosClientId: '101486068607-lt5fb9s281po9h2dmfqg7k5sf3aamp06.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxTutorial',
  );
}
